### ISSUE TITLE
custom label font

### ISSUE THREAD

**Issue by ipedro** [TaimurAyaz/TAOverlay#6]
setting the font via `+(void)setOverlayLabelFont:` has no effect

**Comment by TaimurAyaz** [comment]
Hmm I just checked. It works for me. Could you explain how you created the control and what you were doing?

**Comment by TaimurAyaz** [comment]
Are you calling the method before or after [TAOverlay show.....] ? It would not work if you change the properties before showing since the overlay is dynamically created on the show methods. To change the properties on init, do something like so:

....
....
[TAOverlay show....];
[TAOverlay setOverlayLabelFont....];
....
....

Let me know if that works out for you.

**Comment by ipedro** [comment]
Ah, I get it
I was setting it once, before any calls. Thanks for pointing that out.

**Comment by TaimurAyaz** [comment]
I will be pushing an update today or tomorrow. This update would let you set properties before hand as well. So it would work in your case.

**Comment by TaimurAyaz** [comment]
Its up. You should be able to set font and/or other properties before calling show functions
